export const DataView: string;
export const viewTitleRow: string;
export const viewTitle: string;
export const viewTitleButtonsRow: string;
export const alertContainer: string;
export const alertLink: string;
export const KpiTilesContainer: string;
export const kpiTreesSubtitle: string;
export const measureInDetailBoardRightNodeLabel: string;
