export const CollapsibleContentBoard: string;
export const headerContainer: string;
export const collapseButtonContainer: string;
export const title: string;
export const rightNodeContainer: string;
export const childrenContainer: string;
export const expanded: string;
export const headerIsSticky: string;
export const headerHighlighted: string;
